cabal-version:      3.0
name:               TREES
version:            0.1.0.0
license:            AGPL-3.0-or-later
license-file:       LICENSE
author:             Júlio César Borges de Oliveira Sampaio
maintainer:         juliocesarborgesdeoliveir@gmail.com
-- copyright:
category:           Data
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

executable TREES
    import:           warnings
    main-is:          Tree.hs
    build-depends: 
        base ^>=4.18.2.1,
        containers ^>=0.6.7
    hs-source-dirs:   app
    default-language: Haskell2010
    ghc-options: -fno-warn-tabs